### ISSUE TITLE
Will this converter be added to Retrofit repo?

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JakeWharton/retrofit2-kotlinx-serialization-converter#10]
Hey @JakeWharton, will you add this converter to the Retrofit repo or will it be here forever?

**Comment by JakeWharton** [comment]
Only libraries with stable APIs are added to Retrofit directly and this is not a stable library.

**Comment by JavierMeep** [comment]
Wake Me Up When September Ends
