### ISSUE TITLE
FromString converter question?

### ISSUE THREAD

**Issue by gajicm93** [JakeWharton/retrofit2-kotlinx-serialization-converter#19]
https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter/blob/82b8aef7568719c1290ad7c67029fbbd90483780/src/main/java/com/jakewharton/retrofit2/converter/kotlinx/serialization/Serializer.kt#L17

Why does JSON by default use FromString converter and parses whole response body as a String, instead streaming bytes?

I know this can crash some devices when the payload is too large, and there are limitations about how long a String object can be, and it's also less optimized from network perspective instead of streaming response? Also I know Gson converter doesn't do this.. So why, and are there any plans to change this?

Thanks.

**Comment by JakeWharton** [comment]
The serialization library does not support streaming.

https://github.com/Kotlin/kotlinx.serialization/issues/204
