### ISSUE TITLE
lang.IllegalArgumentException: Unable to create @Body converter for class c.g.a.c.a.f.b (parameter #1)         for method e.a

### ISSUE THREAD

**Issue by hnabtiti** [JakeWharton/retrofit2-kotlinx-serialization-converter#22]
fun createRetrofitInstance(okHttpClient: OkHttpClient, converter: Converter.Factory): Retrofit {
    return Retrofit.Builder()
        .baseUrl(STAGING_URL)
        .client(okHttpClient)
        .addConverterFactory(converter).build()
}

**Comment by hnabtiti** [comment]
: java.lang.IllegalArgumentException: Unable to create @Body converter for class c.g.a.c.a.f.b (parameter #1)
        for method e.a
W/Authentication: o.h0.a()
W/Authentication: o.h0.a()
W/Authentication: o.e0.a(:37)
W/Authentication: o.d0.a()
W/Authentication: o.d0$a.invoke(:2)
W/Authentication: java.lang.reflect.Proxy.invoke(Proxy.java:397)
W/Authentication: $Proxy0.a(Unknown Source)
W/Authentication: c.g.a.c.a.d.a(:2)
W/Authentication: c.g.a.g.f.e.c(:4)
W/Authentication: k.q.j.a.a.a()
W/Authentication: h.a.j0.run(:4)
W/Authentication: h.a.t1.a.a()
 W/Authentication: h.a.t1.a$a.run(:9)

**Comment by JakeWharton** [comment]
What's the deobfuscated trace?

**Comment by prudhvir3ddy** [comment]
@JakeWharton facing the same issue 

     Caused by: g.b.v: Can't locate argument-less serializer for class a. For generic classes, such as lists, please provide serializer explicitly.

**Comment by prudhvir3ddy** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/946

**Comment by JakeWharton** [comment]
Without a deobfuscated trace it's impossible to know what's going on. An executable sample would be even better.

**Comment by prudhvir3ddy** [comment]
@hnabtiti check the issue Kotlin/kotlinx.serialization#946

it's just that models might be in a different modele for which you might not have applied the proguard rules
