### ISSUE TITLE
Incompatibility with coroutines

### ISSUE THREAD

**Issue by DRSchlaubi** [JakeWharton/retrofit2-kotlinx-serialization-converter#33]
``` 
@GET("catalog/categories")
    suspend fun getAllCategories(
        @Query("is_visible") isVisible: Boolean = true,
        @Query("parent_id") parentId: Int? = 0,
        @Query("page") page: Int? = null,
        @Query("limit") limit: Int? = null,
        @Query("productId:in") ids: String? = null
    ): CategoriesResponse```
This method fails as soon as adding the suspend keyword with:
```
```
kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for missing class discriminator ('null')
JSON input: .....current":"?is_visible=true&parent_id=36&page=1&limit=50"}}}}
```
Full stacktrace: https://pastebin.com/EDVHTcJ6

As soon as I removed the`suspend` keyword the request works again normally

# Versions
Kotlin: 1.4.10
OkHttp: 4.8.1
retrofit: 2.9.0
converter: 0.6.0

**Comment by DRSchlaubi** [comment]
Looks like when making the function suspending the type becomes a`retrofit2.Call<T>` which kx.ser than tries to convert but failes

**Comment by DRSchlaubi** [comment]
The problem may be this line
https://github.com/square/retrofit/blob/576f23dae73814b23787322d8f663c4421af8939/retrofit/src/main/java/retrofit2/HttpServiceMethod.java#L60 in comparison to this
https://github.com/square/retrofit/blob/576f23dae73814b23787322d8f663c4421af8939/retrofit/src/main/java/retrofit2/HttpServiceMethod.java#L63

**Comment by JakeWharton** [comment]
That is how it works internally in Retrofit, but `T` is then extracted and supplied to the converter factory. Removing the `suspend` keyword in your sample should cause Retrofit to throw an exception because that is not a valid return type. It would need to be `Call<CategoriesResponse>` or `Observable<CategoriesResponse>` or something of that nature.

Can you provide a failing test case or executable sample that shows your setup and the failure?

**Comment by DRSchlaubi** [comment]
The thing is
it actually does not removing the suspend works completely fine

**Comment by JakeWharton** [comment]
Without a failing test case or executable sample I have no way of knowing what you are seeing.

**Comment by DRSchlaubi** [comment]
```kt
val LOG = KotlinLogging.logger {}

object CallAdapterFactory : CallAdapter.Factory() {
    override fun get(returnType: Type, annotations: Array<Annotation>, retrofit: Retrofit): CallAdapter<*, *> =
        CallAdapterImpl(returnType)

    class CallAdapterImpl(private val type: Type) : CallAdapter<Any, Any?> {

        override fun adapt(call: Call<Any>): Any? {
            val response = call.execute()
            LOG.debug { "Got response: ${call.request().url} => ${response.code()}: ${response.message()}" }
            return when {
                response.code() == 404 -> null
                response.code() in 200..299 -> response.body()
                else -> {
                    throw RestException(
                        response.code(),
                        response.errorBody()?.string() ?: response.body()?.toString() ?: response.message()
                    )
                }
            }
        }

        override fun responseType(): Type = type
    }
}

/**
 * Exception that is throws if the REST request returns an unexpected error code.
 *
 * @property code the response code
 * @property errorMessage the message of the error
 */
class RestException(val code: Int, val errorMessage: String) : IllegalArgumentException("$code: $errorMessage")
```

I guess the issue is my own call adapter here?

But for some reason if I do not use suspend the type parameter of CallAdapter.Facotry#get() is the actual return type if I make it suspend it is call

**Comment by DRSchlaubi** [comment]
That's an issue with my calladapter i now fixed
