### ISSUE TITLE
deserialization not happening for properties with different names than original

### ISSUE THREAD

**Issue by BlueTurtle7** [JakeWharton/retrofit2-kotlinx-serialization-converter#38]
Hello,

I'm using kotlin serialization - 1.0.0-RC2, Kotlin 1.4.0, converter 0.8.0.

It appears that each time the property name is different from the original name in **@SerialName** the property isn't updated. for instance:

@SerialName("name_de")
    var nameDe: String? = ""

nameDe stays empty even though has a different value in the Json response.

my Retrofit configuration is:
`Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addConverterFactory(Json { isLenient = true; ignoreUnknownKeys = true; allowStructuredMapKeys = true; prettyPrint = true; coerceInputValues = true; }.asConverterFactory(contentType))
            .client(okHttpClient)
            .build()`

Thanks

**Comment by Mitti30** [comment]
Hey man, did you solve it? I'm facing the same Problem.

**Comment by BlueTurtle7** [comment]
Yes I was using  a Jackson seralizer mistakenly as I am using Jackson in another part of the app. There was no bug. I realized that while debugging my retrofit object.
