### ISSUE TITLE
Update Dependencies 

### ISSUE THREAD

**Issue by omarshaarawi** [JakeWharton/retrofit2-kotlinx-serialization-converter#45]
I'd like to create a PR that would update all dependencies but notably kotlinx-serialization to 1.3.0. Notable improvements in 1.3.0: 
- Promote JsonConfiguration and its usages to stable (#1690)
- Remove opt-in annotations from SerialFormat, StringFormat, BinaryFormat (#1688)

https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.3.0

Is there any harm/concern is raising a PR to get at least this updated?

**Comment by JakeWharton** [comment]
I don't think any of those change affect the code of the library. I fully expect downstream consumers to be using the latest versions of both Kotlin and kotlinx.serialization. Relying on the transitive dependencies of this library to dictate your version of Kotlin and kotlinx.serialization is a bad idea, so I tend to only update when there is something that actually benefits this library directly.

**Comment by omarshaarawi** [comment]
>  Relying on the transitive dependencies of this library to dictate your version of Kotlin and kotlinx.serialization is a bad idea

That's a fair point that took me too long to realize. Will close the issue
