### ISSUE TITLE
[Question] Does the decoder ignoreUnknownKeys?  

### ISSUE THREAD

**Issue by SeanOThomas** [JakeWharton/retrofit2-kotlinx-serialization-converter#47]
I'm doing a little discovery before picking up this tool. I'm wondering if the decoder has ignoreUnknownKeys on by default, or if that can be configured? Same with other fields like explicitNulls. Thanks in advance!

**Comment by JakeWharton** [comment]
This library is just a bridge between kotlinx.serialization and Retrofit. The library does not influence or affect the behavior of kotlinx.serialization in any way–it merely translates the Retrofit APIs to kotlinx.serialization for requests and vise-versa for responses. Moreover, kotlinx.serialization is a framework for multiple serialization formats each of which have their own behaviors and configuration. You can learn all about them at https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serialization-guide.md.
