### ISSUE TITLE
Escaping Characters

### ISSUE THREAD

**Issue by rtsketo** [JakeWharton/retrofit2-kotlinx-serialization-converter#49]
The converter seems somehow to be escaping the `=` symbol.

For example in a JSON ` "bearerToken": "...205onD2fVY1/t2AE="` becomes ` "bearerToken": "...205onD2fVY1/t2AE\u003d"`

I tried kotlinx seriliazation by itself on the same object and it doesn't escape it. I'm using the following configuration.
```
Json {
        coerceInputValues = true
        ignoreUnknownKeys = true   }
```

Is this a bug or a feature?
Is there a way to disable it?

**Comment by JakeWharton** [comment]
This library is just an adapter between Retrofit and kotlinx.serialization that knows nothing about the actual serialization mechanism. If you have questions or bugs to report please do so on https://github.com/Kotlin/kotlinx.serialization.
