### ISSUE TITLE
remove ExperimentalSerializationApi

### ISSUE THREAD

**Issue by xanscale** [JakeWharton/retrofit2-kotlinx-serialization-converter#50]
since kotlinx.serialization has become stable, I think it is necessary to stabilize this library as well

**Comment by JakeWharton** [comment]
The reflective APIs are not stable: https://github.com/Kotlin/kotlinx.serialization/blob/v1.3.1/core/jvmMain/src/kotlinx/serialization/SerializersJvm.kt#L57-L59
