### ISSUE TITLE
Fatal Exception: kotlinx.serialization.MissingFieldException

### ISSUE THREAD

**Issue by ghost** [JakeWharton/retrofit2-kotlinx-serialization-converter#54]
how to parse only needed properties from API JSON no need for all properties to be parsed

non of the following works:

Json {
this.coerceInputValues = true
this.encodeDefaults = true
this.isLenient = true
this.ignoreUnknownKeys = true
this.prettyPrint = true
this.coerceInputValues = true
}.asConverterFactory(contentType)

**Comment by JakeWharton** [comment]
This library is just an adapter so that Retrofit will delegate to kotlinx.serialization. If you have questions or issues with kotlinx.serialization usage you should ask on StackOverflow, the Kotlinlang Slack, or on kotlinx.serialization's issue tracker.
