### ISSUE TITLE
Support JsonNames

### ISSUE THREAD

**Issue by Jparrgam** [JakeWharton/retrofit2-kotlinx-serialization-converter#56]
Hi, I have an error when integrating the converter, I am using [@JsonNames](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json-names/) to be able to send and receive multiple names in the values but it's not taking it the right way use the property name not the annotation value, using @SerialName if it does

**Comment by JakeWharton** [comment]
This library is just for supplying the response body stream or string to your chosen BinaryFormat or TextFormat from kotlinx.serialization. It does not participate in the actual parsing of data or binding it to your objects. If you're having an issue with JSON serialization, StackOverflow, the Kotlinlang Slack, or the kotlinx.serialization issue tracker are you best bet.
