### ISSUE TITLE
Take in consideration Serialization new update

### ISSUE THREAD

**Issue by catluc** [JakeWharton/retrofit2-kotlinx-serialization-converter#57]
One of the new features of this update: **Integration with Okio’s BufferedSource and BufferedSink.**

Could this be used in order to make more efficient the use of Serialization?
More info: https://blog.jetbrains.com/kotlin/2022/09/kotlin-news-august/#kotlinxserialization_140_Is_Out

**Comment by JakeWharton** [comment]
No. It is only supported for `Json` and not arbitrary `TextFormat`s or `BinaryFormat`s which are the type this library builds against. See #43.
