### ISSUE TITLE
Add default param to asConverterFactory 

### ISSUE THREAD

**Issue by xanscale** [JakeWharton/retrofit2-kotlinx-serialization-converter#60]
the media type for json body are standard and i think could be set as default

`fun StringFormat.asConverterFactory(contentType: MediaType): Converter.Factory`
to
`fun StringFormat.asConverterFactory(contentType: MediaType = "application/json".toMediaType()): Converter.Factory`

**Comment by JakeWharton** [comment]
The format is unknown. JSON is only one of many text-based formats that you may be using (XML, YAML, TOML, CSV, etc.).
